### ISSUE TITLE
KeyError: 'config' by Run the Olive workflow to generate the optimized model

### ISSUE THREAD

**Issue by ggchiu** [microsoft/ai-powered-notes-winui3-sample#7]
**When I follow all the steps in the Readme until step 4...**

```
(olive_env) C:\Users\simonchiu\Olive\examples\whisper>olive run --config whisper_cpu_int8.json --setup
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\simonchiu\olive_env\Scripts\olive.exe\__main__.py", line 7, in <module>
  File "C:\Users\simonchiu\olive_env\Lib\site-packages\olive\cli\launcher.py", line 44, in main
    service.run()
  File "C:\Users\simonchiu\olive_env\Lib\site-packages\olive\cli\run.py", line 42, in run
    olive_run(**var_args)
  File "C:\Users\simonchiu\olive_env\Lib\site-packages\olive\workflows\run\run.py", line 284, in run
    run_config = RunConfig.parse_file_or_obj(run_config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\simonchiu\olive_env\Lib\site-packages\olive\common\config_utils.py", line 127, in parse_file_or_obj
    return cls.parse_file(file_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\simonchiu\olive_env\Lib\site-packages\pydantic\v1\main.py", line 569, in parse_file
    return cls.parse_obj(obj)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\simonchiu\olive_env\Lib\site-packages\pydantic\v1\main.py", line 526, in parse_obj
    return cls(**obj)
           ^^^^^^^^^^
  File "C:\Users\simonchiu\olive_env\Lib\site-packages\pydantic\v1\main.py", line 339, in __init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\simonchiu\olive_env\Lib\site-packages\pydantic\v1\main.py", line 1074, in validate_model
    v_, errors_ = field.validate(value, values, loc=field.alias, cls=cls_)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\simonchiu\olive_env\Lib\site-packages\pydantic\v1\fields.py", line 864, in validate
    v, errors = self._apply_validators(v, values, loc, cls, self.pre_validators)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\simonchiu\olive_env\Lib\site-packages\pydantic\v1\fields.py", line 1154, in _apply_validators
    v = validator(cls, v, values, self, self.model_config)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\simonchiu\olive_env\Lib\site-packages\pydantic\v1\class_validators.py", line 306, in <lambda>
    return lambda cls, v, values, field, config: validator(cls, v, values=values)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\simonchiu\olive_env\Lib\site-packages\olive\workflows\run\config.py", line 161, in insert_aml_client
    input_model_path = v["config"].get("model_path")
                       ~^^^^^^^^^^
KeyError: 'config'
``` 
Python version: 3.12.4

I checked 'whisper_cpu_int8.json' and there is indeed no key named "config". I'm not sure if the problem is related to this, I'm looking forward to your answer. Thanks!

**Comment by nmetulev** [comment]
I haven't seen this, and I'd recommend posting this issue on the Olive repo.

In the meantime, there are pre-built models here that I've tried and work that you can use to unblock you: https://huggingface.co/khmyznikov/whisper-int8-cpu-ort.onnx/tree/main

**Comment by ggchiu** [comment]
First, thank you for providing a model that I can run successfully.


Then I still keep trying to build the model, and changed the steps to
```
git clone -b rel-0.6.2 https://github.com/microsoft/Olive.git
``` 
Finally, the model ```whisper_cpu_int8_cpu-cpu_model.onnx``` was successfully established.

But..., as shown in the picture
![螢幕擷取畫面 2024-08-23 151815](https://github.com/user-attachments/assets/79a4486a-3594-44e8-b61e-c083ae96a762)

The package in Notes is
![螢幕擷取畫面 2024-08-23 152018](https://github.com/user-attachments/assets/b7773e85-cbe9-4183-ad51-641efc79253d)

and the package in my virtual environment is
```
olive-ai               0.6.2
onnx                   1.16.2
onnxruntime            1.18.0
onnxruntime_extensions 0.12.0
``` 

I tried install the correct version but it didn't work.
```
(olive_env) C:\Users\simonchiu\Olive\examples\whisper>pip install onnxruntime_extensions==0.10.0
ERROR: Could not find a version that satisfies the requirement onnxruntime_extensions==0.10.0 (from versions: 0.10.1, 0.11.0, 0.12.0)
ERROR: No matching distribution found for onnxruntime_extensions==0.10.0
``` 

I'm not sure if there is something else causing the error, could you tell me what version of the package you had in your environment when you built the model? Or maybe the cause is no longer this.

Thanks for reading!

**Comment by beth-panx** [comment]
Hello! The error is due to the rapid changes happening with Olive. Can you try `pip uninstall -y olive-ai` and then `pip install git+https://github.com/microsoft/Olive`?

**Comment by ggchiu** [comment]
HI, I've tried `pip install git+https://github.com/microsoft/Olive

It solves the problem of building the model that I mentioned before very well.


But the model I built still has the following problems:
![螢幕擷取畫面 2024-08-23 151815](https://github.com/user-attachments/assets/368315a8-6bf5-4b4b-aa3f-2bba5a4e9247)

However, the model provided at https://huggingface.co/khmyznikov/whisper-int8-cpu-ort.onnx/tree/main can run successfully.

This is the question I'm curious about now, thank you

**Comment by ggchiu** [comment]
Sorry, have you tried following the latest steps to build a model and encountered this problem?
I still don't have a solution
